# Enable Doctrine to map the provided entities
sonata_customer:
    class:
        customer: AppBundle\Entity\Customer
        address:  AppBundle\Entity\Address
        order:    AppBundle\Entity\Order
        user:     AppBundle\Entity\User

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataCustomerBundle: ~