# Enable Doctrine to map the provided entities
sonata_order:
    class:
        order:         AppBundle\Entity\Order
        order_element: AppBundle\Entity\OrderElement
        customer:      AppBundle\Entity\Customer

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataOrderBundle: ~
